name: boot-framework-build
on: [push]
jobs:
  maven_clean_deploy:
    name: Build and publish Repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          check-latest: true
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
      - name: Test with Gradle
        if: github.ref_type == 'branch' && !(startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
        run: gradle -Partifactory.password=${{ secrets.GITHUB_TOKEN }} -Partifactory.user=${{ github.actor }} build
      - name: Release with Gradle
        if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'main'))
        run: git config user.email "release-bot@example.com" && git config user.name "release-bot" && gradle -Prelease.useAutomaticVersion=true -Partifactory.password=${{ secrets.GITHUB_TOKEN }} -Partifactory.user=${{ github.actor }} release
    timeout-minutes: 10