name: boot-framework-build
on: [push]
jobs:
  maven_clean_verify:
    name: Build and Test Repo
    if: github.ref_type == 'branch' && startsWith(github.ref_name, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --show-version verify
    timeout-minutes: 10
  maven_clean_deploy:
    name: Build and publish Repo
    if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --show-version deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release version
        run: mvn --batch-mode release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Release version
#        uses: qcastel/github-actions-maven-release@master
#        env:
#          JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          git-release-bot-name: "release-bot"
#          git-release-bot-email: "release-bot@example.com"
#          release-branch-name: "main"
#          version-patch: true
#          access-token: ${{ secrets.GITHUB_TOKEN }}
#          maven-servers: ${{ secrets.MVN_REPO_SERVERS }}
    timeout-minutes: 10