name: boot-framework-build
on: [push]
jobs:
  maven_clean_verify:
    name: Build and Test Repo
    if: github.ref_type == 'branch' && startsWith(github.ref_name, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --show-version verify
    timeout-minutes: 10
  maven_clean_deploy:
    name: Build and publish Repo
    if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'main'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          check-latest: true
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --show-version deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10